name: Angular build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}        
      
      - name: Install dependencies
        run: npm ci    
      - run: npm run build --if-present   

      - name: Remove File and Copy File to Root
        run: |    
          mkdir ../temp
          cp -R build/* ../temp      

      - name: Create release branch
        run: |
          git fetch
          git checkout -b release origin/release

      - name: Initialize mandatory git config
        run: |
          git config user.name "Automatic Build"
          git config user.email noreply@github.com 
          
      - name: Commit build data
        id: make-commit
        run: |
          git rm -r *
          cp ../temp .
          find . -mindepth 1
          git add *
          git commit --message "Prepare release"
          echo "::set-output name=commit::$(git rev-parse HEAD)"

      - name: Push new branch
        run: git push origin release